name: Release exists
description: Checks if the provided release exists

inputs:
  github_token:
    type: string
    required: true
  tag:
    type: string
    required: true

outputs:
  exists:
    value: ${{ steps.check-release-exists.outputs.exists }}

runs:
  using: composite
  steps:
    - id: check-release-exists
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        TAG: ${{ inputs.tag }}
      run: |
        if gh release view "$TAG" >/dev/null 2>&1; then
          exists=true
        else
          exists=false
        fi
        echo "Release '$TAG' exists: $exists"
        echo "exists=$exists" >> "$GITHUB_OUTPUT"
