name: Create tag
description: Create a new tag

inputs:
  tag:
    type: string
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      env:
        TAG: ${{ inputs.tag }}
      run: |
        echo "Creating tag: $TAG"
        git tag -a "$TAG" -m "Version $TAG"
        git push origin "$TAG"
