name: Create release
description: Create a new release

inputs:
  github_token:
    type: string
    required: true
  tag:
    type: string
    required: true
  draft:
    type: boolean
    required: false
    default: false
  prerelease:
    type: boolean
    required: false
    default: false

runs:
  using: composite
  steps:
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        TAG: ${{ inputs.tag }}
        DRAFT: ${{ inputs.draft }}
        PRERELEASE: ${{ inputs.prerelease }}
      run: |
        if [ "$DRAFT" == "true" ]; then
          if [ "$PRERELEASE" == "true" ]; then
            echo "Creating draft pre-release: $TAG"
            gh release create "$TAG" --generate-notes --draft --prerelease
          else
            echo "Creating draft release: $TAG"
            gh release create "$TAG" --generate-notes --draft
          fi
        else
          echo "Creating release: $TAG"

          if [ "$PRERELEASE" == "true" ]; then
            echo "Creating pre-release: $TAG"
            gh release create "$TAG" --generate-notes --prerelease
          else
            echo "Creating release: $TAG"
            gh release create "$TAG" --generate-notes
          fi
        fi
